TEXTS = {
    'pt': {
        'welcome_bonus': "🎉 Parabéns! Você acabou de ganhar R$ {bonus:.2f} SM em bônus no nosso cassino gamificado!\n\nUse seus SM para jogar, testar sua sorte e aprender as mecânicas.\nQuando quiser, é só clicar em Depositar ou Sacar.",
        'select_lang': "Escolha seu idioma / Choose your language:",
        'main_menu': "🎰 Menu Principal\nSaldo: R$ {balance:.2f} SM",
        'btn_tiger': "🐯 Tigrinho",
        'btn_aviator': "✈️ Aviator",
        'btn_roleta': "🎯 Roleta",
        'btn_perfil': "👤 Perfil",
        'btn_ranking': "🏆 Ranking",
        'btn_deposit': "💰 Depositar",
        'btn_withdraw': "🏧 Sacar",
        'deposit_msg': "🔥 Pronto pra jogar com dinheiro real?\nDeposite agora na casa oficial e multiplique seus ganhos!",
        'withdraw_msg': "💸 Hora de transformar bônus em dinheiro de verdade!\nCrie sua conta na casa oficial para sacar seus ganhos.",
        'btn_play_official': "🎰 Jogar na Casa Oficial",
        'btn_withdraw_official': "🏧 Sacar na Casa Oficial",
        'win_limit_reached': "🔥 VOCÊ ATINGIU O LIMITE DE GANHO!\nVocê já faturou R$ {balance:.2f} SM 🎉\n\n👉 Para continuar jogando e sacar dinheiro real, acesse agora:",
        'game_blocked': "🚫 Seus jogos estão bloqueados pois você atingiu o limite de ganhos simulados.\n\nSaque seus ganhos reais aqui: {link}",
        'profile': "👤 PERFIL\n\n🆔 ID: {user_id}\n💰 Saldo: R$ {balance:.2f} SM\n📈 Ganhos Totais: R$ {total_won:.2f} SM",
        'ranking_title': "🏆 TOP 10 JOGADORES",
        'tiger_win': "🐯 O TIGRINHO SOLTOU A CARTA! 🐯\n\nVocê ganhou: R$ {amount:.2f} SM!",
        'tiger_loss': "🐯 O Tigrinho não estava de bom humor... Tente novamente!",
        'aviator_win': "✈️ O avião decolou e você parou a tempo! ✈️\n\nVocê ganhou: R$ {amount:.2f} SM!",
        'aviator_loss': "✈️ O avião voou para longe... Você perdeu!",
        'roleta_win': "🎯 A bola parou no seu número! 🎯\n\nVocê ganhou: R$ {amount:.2f} SM!",
        'roleta_loss': "🎯 Não foi dessa vez na roleta!",
    },
    'en': {
        'welcome_bonus': "🎉 Congratulations! You just won U$D {bonus:.2f} SM bonus in our gamified casino!\n\nUse your SM to play, test your luck, and learn the mechanics.\nWhenever you want, just click Deposit or Withdraw.",
        'select_lang': "Choose your language:",
        'main_menu': "🎰 Main Menu\nBalance: U$D {balance:.2f} SM",
        'btn_tiger': "🐯 Tiger Slot",
        'btn_aviator': "✈️ Aviator",
        'btn_roleta': "🎯 Roulette",
        'btn_perfil': "👤 Profile",
        'btn_ranking': "🏆 Ranking",
        'btn_deposit': "💰 Deposit",
        'btn_withdraw': "🏧 Withdraw",
        'deposit_msg': "🔥 Ready to play with real money?\nDeposit now at the official house and multiply your winnings!",
        'withdraw_msg': "💸 Time to turn bonuses into real money!\nCreate your account at the official house to withdraw your winnings.",
        'btn_play_official': "🎰 Play at Official House",
        'btn_withdraw_official': "🏧 Withdraw at Official House",
        'win_limit_reached': "🔥 YOU’VE REACHED THE WIN LIMIT!\nYou already won U$D {balance:.2f} SM 🎉\n\n👉 To keep playing and cash out real money, access now:",
        'game_blocked': "🚫 Your games are blocked because you reached the simulated win limit.\n\nWithdraw your real winnings here: {link}",
        'profile': "👤 PROFILE\n\n🆔 ID: {user_id}\n💰 Balance: U$D {balance:.2f} SM\n📈 Total Won: U$D {total_won:.2f} SM",
        'ranking_title': "🏆 TOP 10 PLAYERS",
        'tiger_win': "🐯 THE TIGER RELEASED THE CARD! 🐯\n\nYou won: U$D {amount:.2f} SM!",
        'tiger_loss': "🐯 The Tiger wasn't in a good mood... Try again!",
        'aviator_win': "✈️ The plane took off and you stopped in time! ✈️\n\nYou won: U$D {amount:.2f} SM!",
        'aviator_loss': "✈️ The plane flew away... You lost!",
        'roleta_win': "🎯 The ball stopped on your number! 🎯\n\nYou won: U$D {amount:.2f} SM!",
        'roleta_loss': "🎯 Not this time on the roulette!",
    }
}
